export const minutes_past_to: string[] = [
  "%s o'clock",
  "one past %s",
  "two past %s",
  "three past %s",
  "four past %s",
  "five past %s",
  "six past %s",
  "seven past %s",
  "eight past %s",
  "nine past %s",
  "ten past %s",
  "eleven past %s",
  "twelve past %s",
  "thirteen past %s",
  "fourteen past %s",
  "quarter past %s",
  "sixteen past %s",
  "seventeen past %s",
  "eighteen past %s",
  "nineteen past %s",
  "twenty past %s",
  "twenty one past %s",
  "twenty two past %s",
  "twenty three past %s",
  "twenty four past %s",
  "twenty five past %s",
  "twenty six past %s",
  "twenty seven past %s",
  "twenty eight past %s",
  "twenty nine past %s",
  "half past %s",
  "twenty nine to %s",
  "twenty eight to %s",
  "twenty seven to %s",
  "twenty six to %s",
  "twenty five to %s",
  "twenty four to %s",
  "twenty three to %s",
  "twenty two to %s",
  "twenty one to %s",
  "twenty to %s",
  "nineteen to %s",
  "eighteen to %s",
  "seventeen to %s",
  "sixteen to %s",
  "quarter to %s",
  "fourteen to %s",
  "thirteen to %s",
  "twelve to %s",
  "eleven to %s",
  "ten to %s",
  "nine to %s",
  "eight to %s",
  "seven to %s",
  "six to %s",
  "five to %s",
  "four to %s",
  "three to %s",
  "two to %s",
  "one to %s",
  "%s o'clock",
];

export const hour_names = [
  "midnight",
  "one",
  "two",
  "three",
  "four",
  "five",
  "six",
  "seven",
  "eight",
  "nine",
  "ten",
  "eleven",
  "noon",
];

export const weekdays = [
  "sunday the %s",
  "monday the %s",
  "tuesday the %s",
  "wednesday the %s",
  "thursday the %s",
  "friday the %s",
  "saturday the %s",
];

export const midnight = "midnight";

export const noon = "noon";

export const daysOfMonth = [
  "first",
  "second",
  "third",
  "fourth",
  "fifth",
  "sixth",
  "seventh",
  "eighth",
  "ninth",
  "tenth",
  "eleventh",
  "twelfth",
  "thirteenth",
  "fourteenth",
  "fifteenth",
  "sixteenth",
  "seventeenth",
  "eighteenth",
  "nineteenth",
  "twentieth",
  "twenty first",
  "twenty second",
  "twenty third",
  "twenty fourth",
  "twenty fifth",
  "twenty sixth",
  "twenty seventh",
  "twenty eighth",
  "twenty ninth",
  "thirtieth",
  "thirty first",
];
