name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y glib2.0-dev gettext

      - name: Install Yarn v4
        run: |
          corepack enable
          corepack prepare yarn@4.9.4 --activate

      - name: Install dependencies
        run: |
          yarn install --immutable

      - name: Validate and build
        run: |
          make validate

      - name: Create release package
        run: |
          make pack

      - name: Extract version from tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"

      - name: Generate release notes
        id: release_notes
        run: |
          if git describe --tags --abbrev=0 HEAD~1 >/dev/null 2>&1; then
            PREV_TAG=$(git describe --tags --abbrev=0 HEAD~1)
            echo "## Changes since $PREV_TAG" > release_notes.md
            echo "" >> release_notes.md
            git log --pretty=format:"- %s" $PREV_TAG..HEAD >> release_notes.md
          else
            echo "## Changes" > release_notes.md
            echo "" >> release_notes.md
            echo "Initial release" >> release_notes.md
          fi
          echo "Generated release notes:"
          cat release_notes.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Text Clock v${{ steps.version.outputs.version }}"
          body_path: release_notes.md
          files: |
            text-clock@benica.dev.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
