name: Validate

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Yarn v4
        run: |
          corepack enable
          corepack prepare yarn@4.9.4 --activate

      - name: Install dependencies
        run: |
          yarn install --immutable

      - name: Run linting
        run: |
          yarn lint

      - name: Check REUSE compliance
        uses: fsfe/reuse-action@v3

      - name: Run validation
        run: |
          make validate
